services:
  app:
    build:
      context: .
      target: dev
    image: qiita-spring-ecs-rds-app-dev:latest
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '5005:5005'
    networks:
      - app-network

  db:
    image: mysql:8.4.5
    container_name: mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_ROOTPASS}
      MYSQL_DATABASE: ${DEV_DB_DATABASE}
      MYSQL_USER: ${DEV_DB_USERNAME}
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
      LANG: C.UTF-8
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
